# =============================================================================
# cipher.py — Motor criptográfico del algoritmo de cifrado polimórfico OTP
#
# Implementa la "cryptographic box" descrita en el paper:
#   "Cryptography model to secure IoT device endpoints,
#    based on polymorphic cipher OTP"
#   C. Bran, D. Flores, C. Hernández — Universidad Don Bosco, 2019
#
# Este archivo cubre las Secciones II y III del paper:
#   - Sección III-A : Generación de la tabla de llaves (key table generation)
#   - Sección III-B : Mecanismo de cifrado (encryption mechanism)
#   - Sección II    : Campo PSN (Polymorphic Sequence Nibble)
# =============================================================================

import random
import time

class CifradoPolimorfico:

    def __init__(self):
        # ── MASK_64 ────────────────────────────────────────────────────────
        # Máscara de 64 bits usada para confinar todas las operaciones
        # aritméticas dentro del espacio de 64 bits.
        # Requisito (a) de la actividad: "llaves de 64 bits".
        # Paper Sec. III-A: las llaves K1..Kn tienen tamaño de 64 bits.
        self.MASK_64 = 0xFFFFFFFFFFFFFFFF

        # ── keys ───────────────────────────────────────────────────────────
        # Lista que representa la "key table" descrita en el paper.
        # Paper Sec. III-A: "the total number N of keys specified by the
        # pairs is calculated" y se almacena para uso posterior.
        self.keys = []

        # ── last_psn ───────────────────────────────────────────────────────
        # Almacena el último PSN (Polymorphic Sequence Nibble) utilizado.
        # Paper Sec. III-B: "Both pairs store the last PSN that will serve
        # as a selector for the next one using it as a pointer to the next
        # message to be protected."
        self.last_psn = None

        # ── current_key_index ─────────────────────────────────────────────
        # Índice de la llave activa dentro de la tabla de llaves.
        # Implementa el concepto OTP (One-Time Password): cada mensaje
        # cifrado consume una llave diferente de la tabla.
        # Paper Sec. II: "Regular Messages (RM) it represents a normal
        # encrypted message once the peers have constructed the key tables
        # and cipher strategy."
        self.current_key_index = 0


    # =========================================================================
    # SECCIÓN III-A DEL PAPER — Funciones base para la generación de llaves
    #
    # El paper define tres funciones matemáticas livianas elegidas para
    # minimizar el costo computacional en dispositivos IoT embebidos
    # (procesadores de 8 bits o menos). Cada una cumple un rol específico
    # dentro del algoritmo de la Figura 3 del paper.
    # =========================================================================

    def fs(self, x, y):
        # Función "scrambled" (de mezcla) — fs(x, y)
        # Paper Sec. III-A: "The scrambled function fs(x,y) which is applied
        # with one of the received primes and the seed which returns an
        # embryo key P0."
        # Uso en el algoritmo: P0 = fs(P, S)  y  Q0 = fs(Q, S0)
        # Implementada como XOR bitwise por su bajo costo y reversibilidad.
        return x ^ y

    def fg(self, x, y):
        # Función de generación — fg(x, y)
        # Paper Sec. III-A: "The generation function fg(x,y) that uses the
        # embryo key P0 generated by the mixing function and the second
        # prime Q to obtain the first key of the table."
        # Uso en el algoritmo: K1 = fg(P0, Q)  y  K2 = fg(Q0, P0)
        # La multiplicación modular introduce no-linealidad en la llave final.
        return (x * y) & self.MASK_64

    def fm(self, x, y):
        # Función de mutación — fm(x, y)
        # Paper Sec. III-A: "The mutation function fm(x,y) that makes an
        # alteration of the original seed S together with the second prime Q
        # to compute a new seed S0 for the next calculation sequence."
        # Uso en el algoritmo: S0 = fm(S, Q)  y  S1 = fm(S0, P0)
        # La suma modular asegura que la semilla cambie con cada iteración.
        return (x + y) & self.MASK_64


    # =========================================================================
    # SECCIÓN III-A DEL PAPER — Algoritmo de generación de la tabla de llaves
    #
    # Implementa exactamente el diagrama de flujo de la Figura 3 del paper.
    # Recibe P, Q (números primos), S (semilla) y N (número de llaves).
    # Los primos y la semilla mutan en cada iteración del bucle, de forma que
    # ningún par consecutivo de llaves se calcula con los mismos parámetros.
    # =========================================================================

    def generate_keys(self, P, Q, S, N):
        # Reinicia la tabla antes de generar una nueva (FCM o KUM).
        self.keys = []
        self.current_key_index = 0

        while len(self.keys) < N:

            # ── Par de llaves: iteración del bucle (Fig. 3) ───────────────

            # Paso 1 — P0 = fs(P, S)
            # Mezcla el primo P con la semilla S para obtener la llave embrión.
            # Paper: "P0 = fs(P,S)" — nodo superior izquierdo de Fig. 3.
            P0 = self.fs(P, S)

            # Paso 2 — K1 = fg(P0, Q)
            # Genera la primera llave de este par usando P0 y el primo Q.
            # Paper: "K1 = fg(P0,Q)" — primera llave que se agrega a la tabla.
            K1 = self.fg(P0, Q)
            self.keys.append(K1)

            # Si ya tenemos N llaves, salir antes de calcular la segunda del par.
            if len(self.keys) == N:
                break

            # Paso 3 — S0 = fm(S, Q)
            # Muta la semilla original con Q para obtener una nueva semilla.
            # Paper: "S0 = fm(S,Q)" — la semilla cambia en cada iteración.
            S0 = self.fm(S, Q)

            # Paso 4 — Q0 = fs(Q, S0)
            # Genera un nuevo primo embrión Q0 usando la semilla mutada S0.
            # Paper: "Q0 = fs(Q,S0)"
            Q0 = self.fs(Q, S0)

            # Paso 5 — K2 = fg(Q0, P0)
            # Genera la segunda llave del par combinando Q0 con P0.
            # Paper: "K2 = fg(Q0,P0)" — segunda llave que se agrega a la tabla.
            K2 = self.fg(Q0, P0)
            self.keys.append(K2)

            # Paso 6 — S1 = fm(S0, P0)
            # Segunda mutación de la semilla, que será la semilla del próximo ciclo.
            # Paper: "S1 = fm(S0,P0)" — "The seed value mutates with each key
            # computation so the sub-index increases by one."
            S1 = self.fm(S0, P0)

            # Actualiza P, Q y S para el siguiente ciclo del bucle.
            # Paper: "On the other hand the sub-indexes of each prime change
            # with the two-key generation." — los primos también evolucionan.
            P, Q, S = P0, Q0, S1


    # =========================================================================
    # SECCIÓN III-B DEL PAPER — Funciones reversibles fr()
    #
    # Son las funciones aplicadas directamente al payload para cifrarlo.
    # El paper exige que sean reversibles para poder descifrar en el receptor.
    # Paper Sec. III-B: "the set of reversible functions to be applied to
    # the data to be exchanged."
    # Referencias del paper: [15] Garipelly et al. "A Review on Reversible
    # Logic Gates" y [16] Perumalla "Introduction to reversible computing".
    #
    # La elección concreta de estas tres funciones es libre (requisito c de
    # la actividad). El grupo seleccionó: XOR, suma modular y XOR con shift.
    # =========================================================================

    # ── fr1: XOR directa ──────────────────────────────────────────────────────
    def fr1(self, M, K):
        # Cifrado: aplica XOR entre el mensaje M y la llave K.
        # Es autorecíproca: aplicarla dos veces devuelve M.
        return M ^ K

    def fr1_rev(self, C, K):
        # Descifrado: XOR inversa (idéntica a fr1 por propiedad del XOR).
        return C ^ K

    # ── fr2: Suma modular 64 bits ─────────────────────────────────────────────
    def fr2(self, M, K):
        # Cifrado: desplaza el valor del mensaje sumando K módulo 2^64.
        # Introduce difusión aritmética en el texto cifrado.
        return (M + K) & self.MASK_64

    def fr2_rev(self, C, K):
        # Descifrado: resta modular que invierte exactamente la suma.
        return (C - K) & self.MASK_64

    # ── fr3: XOR con desplazamiento de la llave ───────────────────────────────
    def fr3(self, M, K):
        # Cifrado: XOR con la llave desplazada 3 bits a la derecha.
        # El shift introduce variación en el patrón de bits usado como máscara,
        # diferenciando el efecto de fr3 respecto a fr1.
        return M ^ ((K >> 3) & self.MASK_64)

    def fr3_rev(self, C, K):
        # Descifrado: idéntico al cifrado (XOR con la misma máscara deshace la operación).
        return C ^ ((K >> 3) & self.MASK_64)


    # =========================================================================
    # SECCIÓN III-B DEL PAPER — Tabla polimórfica (16 entradas)
    #
    # El PSN es un nibble de 4 bits → 16 valores posibles (0..15).
    # Cada valor mapea a una secuencia de funciones fr() y su orden de aplicación.
    # Esto es el núcleo del "polimorfismo": el mismo mensaje + la misma llave
    # producen textos cifrados distintos dependiendo del PSN activo.
    #
    # Paper Sec. III-B: "The order of application of the reversible functions
    # is determined by the PSN which is dependent on the data to be protected
    # [...] which makes the process non-deterministic since it depends on
    # the data being communicated."
    #
    # Paper Sec. II: "PSN it is a 4-bit part of the message that will change
    # depending on the message being sent and will be used to establish the
    # sequences of reversible functions that are applied to the message."
    # =========================================================================

    def get_function_sequence(self, psn):
        # Retorna la secuencia de funciones de CIFRADO para el PSN dado.
        # Las combinaciones cubren funciones individuales (PSN 0-2),
        # pares (PSN 3-8) y tripletes (PSN 9-15).
        secuencias = {
            0:  [self.fr1],
            1:  [self.fr2],
            2:  [self.fr3],
            3:  [self.fr1, self.fr2],
            4:  [self.fr2, self.fr1],
            5:  [self.fr1, self.fr3],
            6:  [self.fr3, self.fr1],
            7:  [self.fr2, self.fr3],
            8:  [self.fr3, self.fr2],
            9:  [self.fr1, self.fr2, self.fr3],
            10: [self.fr1, self.fr3, self.fr2],
            11: [self.fr2, self.fr1, self.fr3],
            12: [self.fr2, self.fr3, self.fr1],
            13: [self.fr3, self.fr1, self.fr2],
            14: [self.fr3, self.fr2, self.fr1],
            15: [self.fr1, self.fr2, self.fr1]
        }
        return secuencias[psn]

    def get_reverse_sequence(self, psn):
        # Retorna la secuencia de funciones de DESCIFRADO para el PSN dado.
        # IMPORTANTE: el orden es siempre el INVERSO de la secuencia de cifrado,
        # y cada función es reemplazada por su inversa correspondiente.
        # Esto implementa la propiedad de composición de funciones reversibles:
        # si cifrado = f3(f2(f1(M))), entonces descifrado = f1_rev(f2_rev(f3_rev(C))).
        secuencias_reversibles = {
            0:  [self.fr1_rev],
            1:  [self.fr2_rev],
            2:  [self.fr3_rev],
            3:  [self.fr2_rev, self.fr1_rev],
            4:  [self.fr1_rev, self.fr2_rev],
            5:  [self.fr3_rev, self.fr1_rev],
            6:  [self.fr1_rev, self.fr3_rev],
            7:  [self.fr3_rev, self.fr2_rev],
            8:  [self.fr2_rev, self.fr3_rev],
            9:  [self.fr3_rev, self.fr2_rev, self.fr1_rev],
            10: [self.fr2_rev, self.fr3_rev, self.fr1_rev],
            11: [self.fr3_rev, self.fr1_rev, self.fr2_rev],
            12: [self.fr1_rev, self.fr3_rev, self.fr2_rev],
            13: [self.fr2_rev, self.fr1_rev, self.fr3_rev],
            14: [self.fr1_rev, self.fr2_rev, self.fr3_rev],
            15: [self.fr1_rev, self.fr2_rev, self.fr1_rev]
        }
        return secuencias_reversibles[psn]


    # =========================================================================
    # SECCIÓN II DEL PAPER — Extracción del PSN desde el payload
    #
    # El PSN se extrae del propio mensaje que se va a cifrar, no es un valor
    # externo. Esto hace que dependa directamente del contenido del dato,
    # cumpliendo el requisito de no-determinismo del paper.
    #
    # Paper Sec. II: "PSN can be taken from any part of the message and is
    # used as a pointer for the application of the reversible functions and
    # for the PSN of the next message."
    # =========================================================================

    def extract_psn(self, payload, pointer):
        # pointer indica QUÉ nibble del payload se lee como PSN.
        # Se toma módulo 16 para no exceder los 16 nibbles de un entero de 64 bits.
        # Multiplicar por 4 convierte el índice de nibble en un desplazamiento en bits.
        shift = (pointer % 16) * 4

        # Extrae 4 bits (un nibble) del payload en la posición calculada.
        # El resultado es un valor entre 0 y 15, que indexa la tabla polimórfica.
        return (payload >> shift) & 0xF


    # =========================================================================
    # SECCIÓN III-B DEL PAPER — Mecanismo de cifrado (Figura 4)
    #
    # Implementa el flujo completo descrito en la Fig. 4 "Encryption mechanism
    # process": extraer PSN → seleccionar llave → seleccionar funciones →
    # aplicar funciones al payload → producir texto cifrado.
    # =========================================================================

    def encrypt(self, payload, key_index):

        # ── Paso 1: Determinar el PSN ──────────────────────────────────────
        # En el primer mensaje (last_psn es None), el PSN se toma desde la
        # posición 0 del payload.
        # Paper: "for the first exchange is taken from the least significant
        # part of the first message."
        if self.last_psn is None:
            psn = self.extract_psn(payload, 0)
        else:
            # En mensajes posteriores, el PSN anterior actúa como puntero
            # para seleccionar el nibble del nuevo mensaje.
            # Paper: "For the next messages, the previous PSN value serves
            # as a pointer for the selection of the next PSN to be used."
            psn = self.extract_psn(payload, self.last_psn)

        # ── Paso 2: Seleccionar la llave activa ───────────────────────────
        # Se usa current_key_index para implementar OTP: cada mensaje consume
        # una llave distinta de la tabla.
        # Paper Fig. 4: "Select key" — la llave Kn se toma de la tabla generada.
        key = self.keys[self.current_key_index]

        # ── Paso 3: Obtener la secuencia de funciones para este PSN ───────
        # El PSN extraído indexa la tabla polimórfica y devuelve la lista
        # ordenada de funciones fr() a aplicar.
        # Paper Fig. 4: "Select functions" usando el PSN.
        funcs = self.get_function_sequence(psn)

        # ── Paso 4: Aplicar las funciones en cadena sobre el payload ──────
        # Cada función recibe el resultado de la anterior (composición).
        # Paper Fig. 4: "Apply functions to the message" → "Cipher message".
        result = payload
        for f in funcs:
            result = f(result, key)

        # ── Paso 5: Guardar el PSN para el próximo mensaje ─────────────────
        # Paper Sec. III-B: "Both pairs store the last PSN that will serve
        # as a selector for the next one."
        self.last_psn = psn

        # Retorna el texto cifrado y el PSN usado (el cliente lo incluye
        # en el campo PSN del paquete RM para que el servidor pueda descifrar).
        return result, psn


    # =========================================================================
    # SECCIÓN III-B DEL PAPER — Mecanismo de descifrado
    #
    # El receptor aplica las funciones inversas EN ORDEN INVERSO sobre el
    # texto cifrado, usando la misma llave sincronizada.
    # Paper Sec. III-B: "The receiver takes the message from which it extracts
    # the PSN for the selection of functions, applies them in reverse using
    # its own calculated key for decryption."
    # =========================================================================

    def decrypt(self, cipher, key_index, psn):

        # Selecciona la llave del mismo índice que usó el emisor.
        # La sincronización de current_key_index entre cliente y servidor
        # garantiza que ambos usen la misma Kn en cada mensaje.
        key = self.keys[self.current_key_index]

        # Obtiene la secuencia INVERSA de funciones para el PSN recibido.
        # El PSN llega en el campo PSN del paquete RM; no se re-extrae del
        # texto cifrado porque ya viene informado por el emisor.
        funcs = self.get_reverse_sequence(psn)

        # Aplica las funciones inversas en cadena para recuperar el mensaje original.
        result = cipher
        for f in funcs:
            result = f(result, key)

        # Actualiza last_psn en el receptor (simetría con el emisor).
        self.last_psn = psn

        return result


    # =========================================================================
    # AUXILIAR — Visualización de la tabla de llaves
    #
    # No forma parte del protocolo de cifrado, pero cumple el requisito (b)
    # de la actividad: "Evaluar la calidad de la generación de llaves de
    # cifrado en cada punto final basado en el número de llaves especificadas."
    # Permite inspeccionar en consola los valores hexadecimales de cada Kn.
    # =========================================================================

    def print_key_table(self, title="Tabla de Llaves", P=None, Q=None, S=None, N=None):
        print(f"\n{title}")
        
        if P is not None:
            print(f"Semillas Recibidas/Usadas -> P: {P} | Q: {Q} | S: {S} | N: {N}")
            
        print("+" + "-"*8 + "+" + "-"*20 + "+")
        print("| Índice | Valor (Hexadecimal)  |")
        print("+" + "-"*8 + "+" + "-"*20 + "+")
        
        if not self.keys:
            print("| (Tabla vacía)                 |")
        else:
            for i, key in enumerate(self.keys):
                print(f"| K{i+1:<5} | {hex(key):<18} |")
                
        print("+" + "-"*8 + "+" + "-"*20 + "+\n")


    # =========================================================================
    # SECCIÓN III-A DEL PAPER — Generación pseudo-aleatoria de semillas
    #
    # Paper Sec. III-A: "For the definition of these three numbers a
    # pseudo-random process is used using physical parameters of the IoT core,
    # which can be temperature, program counter state or physical line state
    # depending on what is available on the processor."
    #
    # En Python (sin acceso a hardware real) se emula esto combinando:
    #   - P, Q : números primos seleccionados aleatoriamente de una lista.
    #   - S    : XOR entre el timestamp en milisegundos y bits aleatorios
    #            (ruido_termico), simulando la entropía física del dispositivo.
    # =========================================================================

    def generar_semillas_random(self, num_keys=10):
        # Lista de primos grandes disponibles para P y Q.
        # Paper Sec. III-A: "two prime numbers P and Q, one for each IoT pair."
        primos_disponibles = [104729, 1299709, 324161, 49979687, 15485863, 32452843, 86028121]
        
        # P y Q deben ser distintos entre sí.
        P = random.choice(primos_disponibles)
        Q = random.choice([p for p in primos_disponibles if p != P])
        
        # Semilla S: combina tiempo actual + bits aleatorios para mayor entropía.
        # Emula el uso de parámetros físicos del hardware IoT.
        ruido_termico = random.getrandbits(32)
        tiempo_ms = int(time.time() * 1000)
        S = tiempo_ms ^ ruido_termico

        # N: número de llaves a generar en esta sesión.
        N = num_keys
        
        return P, Q, S, N